language: ruby
rvm:
  - 2.1.2
env:
  - BACKEND=acts-as-dag
  - BACKEND=neo4j_ancestry
before_script: 
  - bundle exec rake neo4j:install neo4j:get_spatial neo4j:setup neo4j:start
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:migrate